### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by xiayutong** [aesrgan/A-ESRGAN#4]
/media/xyt/software/anaconda3/envs/basicSR/bin/python /media/xyt/data/github/SR/code/A-ESRGAN/train.py -opt options/train_aesrgan_x4plus.yml --debug
2022-02-09 18:17:12,962 INFO: Dataset [RealESRGANDataset] - DF2K is built.
2022-02-09 18:17:12,962 INFO: Training statistics:
	Number of train images: 500
	Dataset enlarge ratio: 1
	Batch size per gpu: 6
	World size (gpu number): 1
	Require iter number per epoch: 84
	Total epochs: 4762; iters: 400000.
Traceback (most recent call last):
  File "/media/xyt/data/github/SR/code/A-ESRGAN/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/media/xyt/software/anaconda3/envs/basicSR/lib/python3.7/site-packages/basicsr/train.py", line 128, in train_pipeline
    model = build_model(opt)
  File "/media/xyt/software/anaconda3/envs/basicSR/lib/python3.7/site-packages/basicsr/models/__init__.py", line 27, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "/media/xyt/software/anaconda3/envs/basicSR/lib/python3.7/site-packages/basicsr/utils/registry.py", line 65, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'RealESRGANModel' found in 'model' registry!"

**Comment by xiayutong** [comment]
请问 options/train_aesrgan_x4plus.yml 的 RealESRGANModel 是 如何定义的，能否直接改成AESRGANModel，我看你里面还有定义
